services:

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - 'mutations_data:/var/lib/postgresql/data'
      - './data/sql:/docker-entrypoint-initdb.d'

volumes:
  mutations_data: null

