services:

  gitlab-runner:
    image: gitlab/gitlab-runner:latest



  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - 'mutations_data:/var/lib/postgresql/data'

volumes:
  mutations_data: null

