"""schema_2_1

Revision ID: dd040736b518
Revises: 96d9f616720a
Create Date: 2024-07-09 10:02:24.920437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dd040736b518"
down_revision: Union[str, None] = "96d9f616720a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "individual_condition",
        sa.Column(
            "primary_diagnosis",
            sa.Boolean(),
            nullable=True,
            comment="The primary diagnosis of the patient's condition in the original excel file",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DROP VIEW IF EXISTS publication_to_database_v CASCADE;
        """
    )

    op.execute(
        """
        DROP VIEW IF EXISTS variant_num_individuals_v CASCADE;
        """
    )

    op.execute(
        """
        DROP VIEW IF EXISTS protien_variant_num_individuals_v CASCADE;
        """
    )

    op.execute(
        """
        DROP VIEW IF EXISTS cpvt_patients_v CASCADE;
        """
    )

    op.execute(
        """
        DROP VIEW IF EXISTS protein_variant_num_cpvt_patients_v CASCADE;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("individual_condition", "primary_diagnosis")
    # ### end Alembic commands ###
