name: Test

on:
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request: { }

env:
  DEFAULT_PYTHON: '3.12'


jobs:

  mypy:
    name: mypy ${{ env.DEFAULT_PYTHON }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Run mypy
        run: poetry run mypy cpvt_database_models


  lint:
    name: lint ${{ env.DEFAULT_PYTHON }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Run lint
        run: poetry run ruff check cpvt_database_models


  test:
    name: test ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs:
      - lint
      - mypy
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          python-version: ${{ matrix.python-version }}

      - name: Run pytest
        run: poetry run pytest --junitxml=report.xml --color=yes --cov=cpvt_database_models --cov-append --cov-report=term-missing -n auto
